language: go
go:
- "1.12.x"
- "1.13.x"
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - develop
  - master
env:
  - GO111MODULE=on
script:
  - make
  - make test
  - make windows
